version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_sihs
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: sistema_sihs
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./01_creacion.sql:/docker-entrypoint-initdb.d/01_creacion.sql
      - ./02_datos_prueba.sql:/docker-entrypoint-initdb.d/02_datos_prueba.sql

volumes:
  postgres_data: